package json_analysis

import (
    "fmt"
    "github.com/mitchellh/mapstructure"
    "testing"
)

func TestJsonMapstructure(t *testing.T) {
    type Person struct {
        Name   string
        Age    int
        Emails []string
    }

    // This input can come from anywhere, but typically comes from
    // something like decoding JSON, generated by a weakly typed language
    // such as PHP.
    input := map[string]interface{}{
        "name":   123,                      // number => string
        "age":    "42",                     // string => number
        "emails": map[string]interface{}{}, // empty map => empty array
    }

    var result Person
    config := &mapstructure.DecoderConfig{
        WeaklyTypedInput: true,
        Result:           &result,
    }

    decoder, err := mapstructure.NewDecoder(config)
    if err != nil {
        panic(err)
    }

    err = decoder.Decode(input)
    if err != nil {
        panic(err)
    }

    fmt.Printf("%#v", result)
}
